FROM golang:1.12.7-alpine3.9
RUN apk add --update git make gcc linux-headers libc-dev

RUN go get github.com/revel/revel && go get github.com/revel/cmd/revel && \
    go get github.com/revel/modules && \
    go get github.com/valyala/fasthttp && go get golang.org/x/crypto/bcrypt && \
    go get gopkg.in/gorp.v2

RUN apk del --purge git make linux-headers

