#!/bin/bash
# shellcheck disable=SC2034

# Host user which can log into master and each worker nodes
HOST_USER=${HOST_USER:-iec}

REPO_URL="https://gerrit.akraino.org/r/iec"
#log file
LOG_FILE="kubeadm.log"


# Master node IP address
K8S_MASTER_IP="10.169.36.152"

# HOST_USER's password on Master node
K8S_MASTERPW="123456"

######################################################
#
#  K8S_WORKER_GROUP is an array which consists of 2
#  parts. One is k8s worker ip address. The other is
#  the user password.
#
######################################################
K8S_WORKER_GROUP=(
"10.169.40.106,123456"
)

# K8s parameter
CLUSTER_IP=172.16.1.136 # Align with the value in our K8s setup script
POD_NETWORK_CIDR=192.168.0.0/16
SVC_CIDR=172.16.1.0/24
#IEC support multiple network solution for Kubernetes: calico,flannel,contivpp,cilium,etc
CNI_TYPE=calico
#kubernetes-cni version 0.7.5/ 0.6.0
CNI_VERSION=0.6.0
#kubernetes version: 1.15.2/ 1.13.0
KUBE_VERSION=1.13.0

# DEV_NAME is an associative array, list network interface device names used by contivpp,
# Use IP address of K8S_WORKER_GROUP as key, for example
#  DEV_NAME=(
#  [10.169.40.106]="enp137s0f0"
#  )
declare -A DEV_NAME
DEV_NAME=()
